In [1]:
import pandas as pd
import os

In [2]:
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_23-56-50
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_22-07-53
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_03-31-49
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-13_05-14-17
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-13_07-39-23
# /hdd/ivny/results/mmlu/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_01-59-48
# /hdd/ivny/results/mmlu/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_03-43-10
# /hdd/ivny/results/mmlu/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-40
# /hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_07-23-22
# /hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen3-8B/2026-01-12_08-44-05
# /hdd/ivny/results/mmlu/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-12_20-11-42
# /hdd/ivny/results/mmlu/dist_lnll/openai/gpt-oss-20b/2026-01-12_05-33-45
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-13_20-24-13
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-13_19-01-11
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_23-09-32
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-14_01-02-48
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_03-24-46
# /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_21-48-52
# /hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_06-21-48
# /hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-31
# /hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_17-52-11
# /hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen3-8B/2026-01-13_01-09-42
# /hdd/ivny/results/trivia_qa/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_08-49-59
# /hdd/ivny/results/trivia_qa/dist_lnll/openai/gpt-oss-20b/2026-01-12_12-22-09

def find_leaf_dirs(root):
    leaf_dirs = []
    for dirpath, dirnames, filenames in os.walk(root):
        if not dirnames:  # no subdirectories → leaf
            leaf_dirs.append(dirpath)
    return leaf_dirs

leaf_dirs = find_leaf_dirs("/hdd/ivny/results")
for d in leaf_dirs:
    if any(x in d for x in ["mmlu", "trivia_qa"]):
        print(d)

/hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_23-56-50
/hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_22-07-53
/hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_03-31-49
/hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-13_05-14-17
/hdd/ivny/results/mmlu/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-13_07-39-23
/hdd/ivny/results/mmlu/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_01-59-48
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-39-10
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-15-08
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-40-49
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-40-06
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-27_10-46-40
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen2.5-7B-Instruct/2026-01-27_09-02-39
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-26_16-47-07
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-27_00-51-25
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_14-34-44
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_23-53-54
/hdd/ivny/results/mmlu/dist_semantic_uncertainty/openai/gpt-oss-20b/2026-01-27_07-14-10
/hdd/ivny/results/mmlu/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_03-43-10
/hdd/ivny/results/mmlu/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-40
/hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_07-23-22
/hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen3-8B/2026-01-12_08-44-05
/hdd/ivny/results/mmlu/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-12_20-11-42
/hdd/ivny/results/mmlu/dist_lnll/openai/gpt-oss-20b/2026-01-12_05-33-45
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-13_20-24-13
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-13_19-01-11
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_23-09-32
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-14_01-02-48
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_03-24-46
/hdd/ivny/results/trivia_qa/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_21-48-52
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-15-15
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-40-08
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-42-25
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-28_02-33-05
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/qwen/Qwen2.5-7B-Instruct/2026-01-28_02-33-32
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-28_02-32-30
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-27_06-19-36
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_21-48-21
/hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/openai/gpt-oss-20b/2026-01-27_18-43-47
/hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_06-21-48
/hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-31
/hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_17-52-11
/hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen3-8B/2026-01-13_01-09-42
/hdd/ivny/results/trivia_qa/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_08-49-59
/hdd/ivny/results/trivia_qa/dist_lnll/openai/gpt-oss-20b/2026-01-12_12-22-09

In [3]:
# Read linguistic_calibration_metrics.csv from all leaf directories
all_metrics = []

for leaf_dir in leaf_dirs:
    if any(x in leaf_dir for x in ["mmlu", "trivia_qa"]):
        metrics_file = os.path.join(leaf_dir, "linguistic_calibration_metrics.csv")
        
        if os.path.exists(metrics_file):
            try:
                df_metrics = pd.read_csv(metrics_file)
                
                # Extract path components for context
                parts = leaf_dir.split("/")
                task = parts[4] if len(parts) > 4 else "unknown"
                method = parts[5] if len(parts) > 5 else "unknown"
                org = parts[6] if len(parts) > 6 else "unknown"
                model = parts[7] if len(parts) > 7 else "unknown"
                timestamp = parts[8] if len(parts) > 8 else "unknown"
                
                # Add metadata columns
                df_metrics["task"] = task
                df_metrics["method"] = method
                df_metrics["organization"] = org
                df_metrics["model"] = model
                df_metrics["timestamp"] = timestamp
                df_metrics["path"] = leaf_dir
                
                all_metrics.append(df_metrics)
                print(f"✓ Loaded {metrics_file}")
            except Exception as e:
                print(f"✗ Error loading {metrics_file}: {e}")
        else:
            print(f"✗ File not found: {metrics_file}")

# Aggregate into one big table
if all_metrics:
    aggregated_metrics = pd.concat(all_metrics, ignore_index=True)
    print(f"\nAggregated shape: {aggregated_metrics.shape}")
    print(f"Unique tasks: {aggregated_metrics['task'].nunique()}")
    print(f"Unique methods: {aggregated_metrics['method'].nunique()}")
    print(f"Unique models: {aggregated_metrics['model'].nunique()}")
    print("\nFirst few rows:")
    display(aggregated_metrics.head(10))
else:
    print("No metrics files found!")

✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_23-56-50/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_22-07-53/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_03-31-49/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-13_05-14-17/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-13_07-39-23/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_01-59-48/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-39-10/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-15-08/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-40-49/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-40-06/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-27_10-46-40/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen2.5-7B-Instruct/2026-01-27_09-02-39/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-26_16-47-07/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-27_00-51-25/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_14-34-44/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_23-53-54/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/mmlu/dist_semantic_uncertainty/openai/gpt-oss-20b/2026-01-27_07-14-10/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_03-43-10/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-40/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_07-23-22/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/qwen/Qwen3-8B/2026-01-12_08-44-05/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-12_20-11-42/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/mmlu/dist_lnll/openai/gpt-oss-20b/2026-01-12_05-33-45/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Llama-3.1-8B-Instruct/2026-01-13_20-24-13/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-13_19-01-11/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen2.5-7B-Instruct/2026-01-13_23-09-32/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/qwen/Qwen3-8B/2026-01-14_01-02-48/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_03-24-46/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_linguistic_confidence/openai/gpt-oss-20b/2026-01-13_21-48-52/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-15-15/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_12-40-08/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Llama-3.1-8B-Instruct/2026-01-26_22-42-25/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-28_02-33-05/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/qwen/Qwen2.5-7B-Instruct/2026-01-28_02-33-32/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/qwen/Qwen3-8B/2026-01-28_02-32-30/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-27_06-19-36/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/mistralai/Mistral-7B-Instruct-v0.3/2026-01-26_21-48-21/linguistic_calibration_metrics.csv
✗ File not found: /hdd/ivny/results/trivia_qa/dist_semantic_uncertainty/openai/gpt-oss-20b/2026-01-27_18-43-47/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Llama-3.1-8B-Instruct/2026-01-12_06-21-48/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/meta-llama/Meta-Llama-3-8B-Instruct/2026-01-12_01-55-31/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen2.5-7B-Instruct/2026-01-12_17-52-11/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/qwen/Qwen3-8B/2026-01-13_01-09-42/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/mistralai/Mistral-7B-Instruct-v0.3/2026-01-14_08-49-59/linguistic_calibration_metrics.csv
✓ Loaded /hdd/ivny/results/trivia_qa/dist_lnll/openai/gpt-oss-20b/2026-01-12_12-22-09/linguistic_calibration_metrics.csv

Aggregated shape: (216, 8)
Unique tasks: 2
Unique methods: 2
Unique models: 6

First few rows:

,metric,value,task,method,organization,model,timestamp,path
0,original_dECE,0.126836,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
1,original_dECE_pt,0.094316,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
2,original_auroc_pt,0.651113,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
3,original_linguistic_dECE,0.195854,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
4,original_linguistic_dECE_pt,0.134357,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
5,original_linguistic_auroc_pt,0.635444,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
6,calibrated_linguistic_dECE,0.177011,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
7,calibrated_linguistic_dECE_pt,0.125461,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
8,calibrated_linguistic_auroc_pt,0.633394,mmlu,dist_linguistic_confidence,meta-llama,Llama-3.1-8B-Instruct,2026-01-12_23-56-50,/hdd/ivny/results/mmlu/dist_linguistic_confide...
9,original_dECE,0.217075,mmlu,dist_linguistic_confidence,meta-llama,Meta-Llama-3-8B-Instruct,2026-01-12_22-07-53,/hdd/ivny/results/mmlu/dist_linguistic_confide...

In [4]:
# Pivot aggregated metrics by task, model, and method
# Create a summary table grouped by dataset, model, and estimation method

pivot_data = []

for (task, model, method), group in aggregated_metrics.groupby(['task', 'model', 'method']):
    row = {
        'dataset': task,
        'model': model,
        'method': method,
    }
    
    # Get all metric values for this group
    for _, metric_row in group.iterrows():
        metric_name = metric_row['metric']
        value = metric_row['value']
        row[metric_name] = value
    
    pivot_data.append(row)

summary_table = pd.DataFrame(pivot_data)

# Sort by dataset, then model, then method
summary_table = summary_table.sort_values(['dataset', 'model', 'method']).reset_index(drop=True)

print(f"Summary table shape: {summary_table.shape}")
print(f"\nColumns: {summary_table.columns.tolist()}")
print("\nSummary by Dataset and Model:")
display(summary_table)

Summary table shape: (24, 12)

Columns: ['dataset', 'model', 'method', 'original_dECE', 'original_dECE_pt', 'original_auroc_pt', 'original_linguistic_dECE', 'original_linguistic_dECE_pt', 'original_linguistic_auroc_pt', 'calibrated_linguistic_dECE', 'calibrated_linguistic_dECE_pt', 'calibrated_linguistic_auroc_pt']

Summary by Dataset and Model:

,dataset,model,method,original_dECE,original_dECE_pt,original_auroc_pt,original_linguistic_dECE,original_linguistic_dECE_pt,original_linguistic_auroc_pt,calibrated_linguistic_dECE,calibrated_linguistic_dECE_pt,calibrated_linguistic_auroc_pt
0,mmlu,Llama-3.1-8B-Instruct,dist_linguistic_confidence,0.126836,0.094316,0.651113,0.195854,0.134357,0.635444,0.177011,0.125461,0.633394
1,mmlu,Llama-3.1-8B-Instruct,dist_lnll,0.085180,0.052141,0.776535,0.439972,0.215331,0.501448,0.150543,0.127453,0.763297
2,mmlu,Meta-Llama-3-8B-Instruct,dist_linguistic_confidence,0.217075,0.201740,0.577754,0.262872,0.210998,0.580377,0.162671,0.096793,0.565510
3,mmlu,Meta-Llama-3-8B-Instruct,dist_lnll,0.179506,0.147490,0.754486,0.440543,0.204575,0.461493,0.147301,0.118265,0.747485
4,mmlu,Mistral-7B-Instruct-v0.3,dist_linguistic_confidence,0.308148,0.253285,0.524833,0.337823,0.281300,0.575813,0.199213,0.138508,0.563867
5,mmlu,Mistral-7B-Instruct-v0.3,dist_lnll,0.324901,0.314749,0.613560,0.439947,0.189798,0.469143,0.153020,0.096386,0.595253
6,mmlu,Qwen2.5-7B-Instruct,dist_linguistic_confidence,0.174697,0.129160,0.585351,0.231503,0.173258,0.585749,0.165560,0.115110,0.572000
7,mmlu,Qwen2.5-7B-Instruct,dist_lnll,0.454573,0.255744,0.767356,0.452696,0.242349,0.479568,0.112399,0.045429,0.573102
8,mmlu,Qwen3-8B,dist_linguistic_confidence,0.177505,0.150222,0.577692,0.235376,0.185585,0.566323,0.167650,0.112656,0.512838
9,mmlu,Qwen3-8B,dist_lnll,0.260753,0.207176,0.714712,0.451280,0.241795,0.484309,0.134185,0.097860,0.665257
10,mmlu,gpt-oss-20b,dist_linguistic_confidence,0.172512,0.130990,0.583757,0.237122,0.176777,0.548549,0.203044,0.170370,0.561083
11,mmlu,gpt-oss-20b,dist_lnll,0.345345,0.184139,0.609797,0.469965,0.330410,0.517076,0.195113,0.176803,0.504125
12,trivia_qa,Llama-3.1-8B-Instruct,dist_linguistic_confidence,0.103679,0.090651,0.788599,0.150861,0.117039,0.776564,0.135964,0.109247,0.771318
13,trivia_qa,Llama-3.1-8B-Instruct,dist_lnll,0.207048,0.201220,0.821345,0.154778,0.106013,0.749094,0.115904,0.080865,0.793841
14,trivia_qa,Meta-Llama-3-8B-Instruct,dist_linguistic_confidence,0.126547,0.107149,0.647229,0.185035,0.145582,0.628603,0.171802,0.130184,0.628141
15,trivia_qa,Meta-Llama-3-8B-Instruct,dist_lnll,0.063925,0.054912,0.718001,0.254771,0.208178,0.548472,0.131083,0.081721,0.712145
16,trivia_qa,Mistral-7B-Instruct-v0.3,dist_linguistic_confidence,0.214990,0.207650,0.678522,0.253821,0.229119,0.626988,0.135263,0.089214,0.591311
17,trivia_qa,Mistral-7B-Instruct-v0.3,dist_lnll,0.104076,0.098849,0.678265,0.259770,0.195813,0.598683,0.133745,0.076788,0.670684
18,trivia_qa,Qwen2.5-7B-Instruct,dist_linguistic_confidence,0.085281,0.095116,0.765031,0.129380,0.095621,0.745348,0.145835,0.115061,0.730800
19,trivia_qa,Qwen2.5-7B-Instruct,dist_lnll,0.067120,0.065267,0.766589,0.303973,0.277776,0.674564,0.124634,0.082475,0.760875
20,trivia_qa,Qwen3-8B,dist_linguistic_confidence,0.263336,0.261615,0.672916,0.302190,0.285548,0.613504,0.134857,0.066877,0.588570
21,trivia_qa,Qwen3-8B,dist_lnll,0.156061,0.154687,0.750925,0.302000,0.276265,0.584276,0.111662,0.054275,0.731728
22,trivia_qa,gpt-oss-20b,dist_linguistic_confidence,0.235753,0.225959,0.755245,0.269754,0.249808,0.738894,0.093482,0.069317,0.724857
23,trivia_qa,gpt-oss-20b,dist_lnll,0.085553,0.071459,0.655325,0.321331,0.282136,0.551815,0.142940,0.090458,0.656204

In [5]:
print("Token Probs")
summary_table.query(""" method == 'dist_lnll' and dataset == 'mmlu' """)[["model", "original_linguistic_dECE", "calibrated_linguistic_dECE"]]

Token Probs

,model,original_linguistic_dECE,calibrated_linguistic_dECE
1,Llama-3.1-8B-Instruct,0.439972,0.150543
3,Meta-Llama-3-8B-Instruct,0.440543,0.147301
5,Mistral-7B-Instruct-v0.3,0.439947,0.153020
7,Qwen2.5-7B-Instruct,0.452696,0.112399
9,Qwen3-8B,0.451280,0.134185
11,gpt-oss-20b,0.469965,0.195113

In [6]:
print("linguistic confidence")
summary_table.query(""" method == 'dist_linguistic_confidence' and dataset == 'mmlu' """)[["model", "original_linguistic_dECE", "calibrated_linguistic_dECE"]]

linguistic confidence

,model,original_linguistic_dECE,calibrated_linguistic_dECE
0,Llama-3.1-8B-Instruct,0.195854,0.177011
2,Meta-Llama-3-8B-Instruct,0.262872,0.162671
4,Mistral-7B-Instruct-v0.3,0.337823,0.199213
6,Qwen2.5-7B-Instruct,0.231503,0.165560
8,Qwen3-8B,0.235376,0.167650
10,gpt-oss-20b,0.237122,0.203044